In [1]:
# Today we are learning about Numpy
# So, what is numpy ? Numpy means Numerical Python
# we have to import numpy as sqlite3.

In [2]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [4]:
len(dir(np))

591

In [5]:
# This all are the numpy fucntion but as a datascientis we have to use few.

In [7]:
np.sqrt(10) #sqrt=square root

3.1622776601683795

In [11]:
np.amin([60,82,25,67,89]) #get minimum value

25

In [10]:
print("Minimum Value in [60,82,25,67,89]: ",np.amin([60,82,25,67,89]))

Minimum Value in [60,82,25,67,89]:   25


In [13]:
np.amax([60,82,25,67,89]) #Get Maximum  Value

89

In [14]:
print("Maximum Value in [60,82,25,67,89]: ",np.amax([60,82,25,67,89]))

Maximum Value in [60,82,25,67,89]:  89


In [15]:
#Rounded off to next number  using ceiling.

In [16]:
np.ceil(29.1) #its means when we use ceil they give roundfigured answer.

30.0

In [18]:
np.ceil(np.sqrt(10))

4.0

In [20]:
np.ceil(34.65) # it will give you round figure values

35.0

In [21]:
np.sqrt([24,76,45,49])

array([4.89897949, 8.71779789, 6.70820393, 7.        ])

In [22]:
np.sum(np.sqrt([24,76,45,49]))

27.324981305147073

In [23]:
np.ceil(np.sum(np.sqrt([24,76,45,49])))

28.0

In [24]:
# Similarly there are many numpy function ,you can explore them for you knowledge purpose .
# But we use limited function in our course let's explore them.

In [25]:
np.array([5,9,13])


array([ 5,  9, 13])

In [26]:
type([5,9,13])

list

In [27]:
xyz=np.array([5,9,13])

In [28]:
type(xyz)

numpy.ndarray

In [29]:
#Two Dimension

In [30]:
a=np.array([[1,2],[3,4],[4,5]])
print("Type - ",a.dtype)

print("\n",a)

Type -  int32

 [[1 2]
 [3 4]
 [4 5]]


In [31]:
type(a)

numpy.ndarray

In [32]:
#  dtype.conversion

In [33]:
np.array([2,5,7,8], dtype = 'float')

array([2., 5., 7., 8.])

In [34]:
#lets check is it convert to string?

np.array([2,5,7,8], dtype = 'str')

array(['2', '5', '7', '8'], dtype='<U1')

In [35]:
a=[1,2]
c=np.array(a)
print(c)

[1 2]


In [37]:
#copy array into other

b=np.asarray(c)
print(b)

[1 2]


In [38]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [40]:
mat = np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
print("Type/class of this object : ", (type(mat)))

Type/class of this object :  <class 'numpy.ndarray'>


In [47]:
print("Here is the marks \n-----------\n",mat,"\n-----------")

Here is the marks 
-----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----------


In [49]:
print("print dimension of this matrix : ",mat.ndim) #ndim gives dimension,2 for a matrix and 1 for vector

print dimension of this matrix :  2


In [50]:
print("size of the matrix : ",mat.size)#size shows total number elements

size of the matrix :  9


In [51]:
print("Shape of the matrix : ",mat.shape)#shape shows how many rows and column

Shape of the matrix :  (3, 3)


In [52]:
print("Data Type of the matrix ; ",mat.dtype)#shoes which type

Data Type of the matrix ;  int32


In [53]:
#arange and linespace

In [54]:
#dont work with python range function

In [57]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
#in numpy range function also work with float number

In [61]:
a=np.arange(10.5,20.4,2)
a

array([10.5, 12.5, 14.5, 16.5, 18.5])

In [62]:
#Reverse Order

In [63]:
print("Every 5th number from 50 in reverse order \n",np.arange(50,-1,-5))


Every 5th number from 50 in reverse order 
 [50 45 40 35 30 25 20 15 10  5  0]


In [69]:
print("linearly space numbers between 1 and 5 \n-----------------")
print(np.linspace(10,40,5),"\n-----------------")

linearly space numbers between 1 and 5 
-----------------
[10.  17.5 25.  32.5 40. ] 
-----------------


In [70]:
#Include end points and check space between the points
#By default endpoint=True
#Bydefaul retstep=False

In [71]:
np.linspace(2.0,3.0,num=4,endpoint=True,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [76]:
np.linspace(2.0,4.0,num =4, endpoint = True , retstep = False)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [77]:
np.linspace(20.5,25.6, num =6)

array([20.5 , 21.52, 22.54, 23.56, 24.58, 25.6 ])

In [80]:
np.linspace(20.5,25.6, num =6, endpoint = False, retstep = True)

(array([20.5 , 21.35, 22.2 , 23.05, 23.9 , 24.75]), 0.8500000000000002)

In [81]:
np.linspace(20.5,25.6, num =6, endpoint = True, retstep = True)

(array([20.5 , 21.52, 22.54, 23.56, 24.58, 25.6 ]), 1.0200000000000002)

In [86]:
#Matrics creation

print("Vector of Zeros \n ------------------\n", np.zeros([5]), "\n-------------------")

Vector of Zeros 
 ------------------
 [0. 0. 0. 0. 0.] 
-------------------


In [87]:
print("Vector of Zeros \n ------------------\n", np.zeros([5,3]), "\n-------------------")

Vector of Zeros 
 ------------------
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
-------------------


In [91]:
print("Vector of one \n ------------------\n", np.ones([5,3]), "\n-------------------")

Vector of one 
 ------------------
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
-------------------


In [92]:
print("Vector of 5 \n ------------------\n", 5*(np.ones([5,3])), "\n-------------------")

Vector of 5 
 ------------------
 [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]] 
-------------------


In [93]:
5*(np.ones([5,3], dtype = "int")) # we can change the data type as well

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [96]:
#Construct diagonal matrix

np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [97]:
x = np.arange(30).reshape(5,6)

In [98]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [101]:
np.arange(30,50,5).reshape(2,2)

array([[30, 35],
       [40, 45]])

In [102]:
#Random Number Generation

In [103]:
import numpy as np

In [104]:
np.random.seed(6)
print("Random number genration (from uniform distribution)")
np.random.rand(6)

Random number genration (from uniform distribution)


array([0.89286015, 0.33197981, 0.82122912, 0.04169663, 0.10765668,
       0.59505206])

In [116]:
np.random.rand(6,4) # Uniform distribution

array([[0.9109522 , 0.46245591, 0.9429037 , 0.04049228],
       [0.10745497, 0.75571959, 0.04177758, 0.45156315],
       [0.81608583, 0.41919774, 0.18995912, 0.84341059],
       [0.10724632, 0.28801859, 0.21696879, 0.46426722],
       [0.31959039, 0.90909418, 0.78562738, 0.70575068],
       [0.13990345, 0.61182134, 0.85149503, 0.92376847]])

In [107]:
b =np.random.rand(6,4,2)

In [108]:
type(b)

numpy.ndarray

In [110]:
b.ndim #check dimension

3

In [121]:
print("Number from normal distribution with zero mean and standard deviation 1 i.e standard noraml \n ")
np.random.randn(6,4) # Normal Distribution

Number from normal distribution with zero mean and standard deviation 1 i.e standard noraml 
 


array([[-0.0328893 ,  0.64656168, -0.1735962 ,  0.41090073],
       [ 1.75440845, -0.74722486, -1.81995834,  1.31659165],
       [ 0.30258949,  0.71339106,  0.73718956, -0.33620004],
       [ 0.20984291, -1.69392935, -0.06434559,  0.1013954 ],
       [-1.15590566, -0.68065002, -0.11487073,  0.32687238],
       [-0.16840314,  1.39313259,  0.74387068,  0.81423222]])

In [132]:
np.random.seed(6)

print("Random integer vector : ",np.random.randint(5,20,10))

Random integer vector :  [15 14  8  9 15 18 15  5 19 14]


In [134]:
print("\n Random integer matrix")
print(np.random.randint(1,30000,(6,7)))


 Random integer matrix
[[10063  7288 25542 24903 24811 27712 19211]
 [28484  1366 29580 20610  5203 22436  9111]
 [13436 12138 10777 11185 28715 26564 21384]
 [22053 12364  9145 11810 28741 27554 18192]
 [26822  7472 14462  7062   252 17538  4106]
 [29821 13233 14438 10795   553  8270 22090]]


In [135]:
#One of the real time example of randint is

In [136]:
def generate_otp():
    otp = np.random.randint(1000,1999,1)
    print("Your OTP is ",otp)
    user_otp = int(input("Please enter the OTP "))
    if user_otp == otp:
        print("Login Successfully")
    else:
        print('Please enter Valid OTP')

In [140]:
generate_otp()

Your OTP is  [1322]
Please enter the OTP 1322
Login Successfully


In [179]:
sk = np.random.randint(8,90, 7)

In [180]:
sk

array([63, 54, 86, 71, 52,  9, 25])

In [156]:
type(sk)

numpy.ndarray

In [157]:
#set minimum and maximum salary using a_min and a_max 

In [158]:
np.clip(sk,a_min=20,a_max=50)# if we use clip method then all maximum and minimum value we can set as per our use

array([50, 36, 50, 50, 42, 36, 50])

In [160]:
#If you want to find actual salary which are less then or greater than some salary use np.where
#np.where gives index detail

In [165]:
np.where(sk< 40) # it is showing index

(array([1, 5], dtype=int64),)

In [166]:
np.where(sk< 50)

(array([1, 4, 5], dtype=int64),)

In [168]:
sk[[1,4,5]] #we can check using index

array([36, 42, 36])

In [171]:
np.where(sk >=50)

(array([0, 2, 3, 6], dtype=int64),)

In [184]:
sk[[0, 2, 3, 6]]

array([63, 86, 71, 25])

In [183]:
np.where(sk==58)

(array([], dtype=int64),)

In [182]:
np.where(sk>50)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [181]:
sk

array([63, 54, 86, 71, 52,  9, 25])

In [186]:
import numpy as np
from numpy.random import randint as ri

In [190]:
a = ri(1,99,30)

In [191]:
a

array([80, 58, 83, 33, 77, 47, 24, 23, 49, 40, 92, 38, 34, 89, 42, 28, 91,
       23, 52, 96, 72, 72,  6, 68, 73, 80, 40, 43,  6, 58])

In [197]:
b= a.reshape(5,2,3) # we can reshape in 3 dimension

In [199]:
b.ndim # we can check the dimension

3

In [200]:
b.shape # we can check the shape

(5, 2, 3)

In [201]:
b.size # we can check the size of the array

30

In [203]:
type(b) # we can check the type as well

numpy.ndarray

In [204]:
b

array([[[80, 58, 83],
        [33, 77, 47]],

       [[24, 23, 49],
        [40, 92, 38]],

       [[34, 89, 42],
        [28, 91, 23]],

       [[52, 96, 72],
        [72,  6, 68]],

       [[73, 80, 40],
        [43,  6, 58]]])

In [206]:
b.min()

6

In [207]:
b.max()

96

In [208]:
b.mean()

53.9

In [209]:
b.sort()

In [210]:
b

array([[[58, 80, 83],
        [33, 47, 77]],

       [[23, 24, 49],
        [38, 40, 92]],

       [[34, 42, 89],
        [23, 28, 91]],

       [[52, 72, 96],
        [ 6, 68, 72]],

       [[40, 73, 80],
        [ 6, 43, 58]]])

In [211]:
# sorting

In [235]:
se = ri(1,100,25)

In [236]:
se.size

25

In [237]:
se.reshape(5,5)

array([[38, 47, 90, 45, 57],
       [46, 38, 74, 61,  2],
       [66, 26, 26, 38, 92],
       [87, 85, 75, 17, 69],
       [99, 55, 96, 67, 13]])

In [238]:
print("\n 5 X 5 matrix of random integer \n",'-'*50,'\n',se)


 5 X 5 matrix of random integer 
 -------------------------------------------------- 
 [38 47 90 45 57 46 38 74 61  2 66 26 26 38 92 87 85 75 17 69 99 55 96 67
 13]


In [239]:
print("\n Here is the sorted matrix along each row \n",'-'*50,'\n',np.sort(se))#default axis=1


 Here is the sorted matrix along each row 
 -------------------------------------------------- 
 [ 2 13 17 26 26 38 38 38 45 46 47 55 57 61 66 67 69 74 75 85 87 90 92 96
 99]


In [240]:
se.sort()

In [241]:
se1 = se.reshape(5,5)

In [242]:
se1.sort(axis = 1)

In [243]:
se1

array([[ 2, 13, 17, 26, 26],
       [38, 38, 38, 45, 46],
       [47, 55, 57, 61, 66],
       [67, 69, 74, 75, 85],
       [87, 90, 92, 96, 99]])

In [246]:
np.sort(se1, axis = 1)

array([[ 2, 13, 17, 26, 26],
       [38, 38, 38, 45, 46],
       [47, 55, 57, 61, 66],
       [67, 69, 74, 75, 85],
       [87, 90, 92, 96, 99]])

In [248]:
# Index and slicing

In [249]:
arr = np.arange(13,30)

In [251]:
arr

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [252]:
arr[7]

20

In [255]:
arr[[2,4,5]]

array([15, 17, 18])

In [257]:
arr[3:6]

array([16, 17, 18])

In [259]:
print("Element up to 4th index are :",arr[4:])

Element up to 4th index are : [17 18 19 20 21 22 23 24 25 26 27 28 29]


In [262]:
print("Element up to 4th index are :",arr[:-1])

Element up to 4th index are : [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]


In [263]:
abc = arr[4:]

In [264]:
abc

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [265]:
print("Element from last backwords : ",abc[-1::-2])

Element from last backwords :  [29 27 25 23 21 19 17]


In [267]:
print("7th elemets from last backword are : ",arr[-1:-8:-2])

7th elemets from last backword are :  [29 27 25 23]


In [268]:
abc

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [269]:
abc[4:8:2]

array([21, 23])

In [271]:
abc[[2,4,9]]

array([19, 21, 26])

In [272]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [273]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [274]:
mat = np.array(my_mat)

In [275]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [278]:
mat[1,2]

6

In [280]:
print("Entire column at index  3:\n",mat[:,1:])

Entire column at index  3:
 [[2 3]
 [5 6]
 [8 9]]


In [284]:
print("\nSubsetting Sub-Matricss\n---------")

print("Matrics with row indices 1 and 2 and column indices 3 and 4\n",mat[1:2,1:2])


Subsetting Sub-Matricss
---------
Matrics with row indices 1 and 2 and column indices 3 and 4
 [[5]]


In [289]:
print(mat,"\n")
mat[1:2,1:2]

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



array([[5]])

In [290]:
mat[1:2,:]

array([[4, 5, 6]])

In [297]:
mat[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [303]:
mat[1:2,[0,2]]

array([[4, 6]])

In [306]:
mat[1,2] = 99

In [311]:
mat[2:3,[1]] = 100

In [312]:
mat

array([[  1,   2,   3],
       [  4,   5,  99],
       [  7, 100,   9]])

In [313]:
#Subsetting-So what is subsetting ? subsetting means when we wann to fetch only few dara from matrix then we use subsetting method.


In [327]:
mat = np.array(ri(10,100,15))

In [332]:
mat1 = mat.reshape(5,3)

In [333]:
type(mat1)

numpy.ndarray

In [334]:
mat1

array([[19, 31, 39],
       [73, 68, 34],
       [76, 30, 44],
       [51, 72, 46],
       [73, 73, 58]])

In [336]:
print('Matrix of random 2 digit number \n-----------\n',mat1)

Matrix of random 2 digit number 
-----------
 [[19 31 39]
 [73 68 34]
 [76 30 44]
 [51 72 46]
 [73 73 58]]


In [340]:
mat1[mat1>50]

array([73, 68, 76, 51, 72, 73, 73, 58])

In [342]:
mat1[mat1<50]

array([19, 31, 39, 34, 30, 44, 46])

In [344]:
np.where(mat1==30)

(array([2], dtype=int64), array([1], dtype=int64))

In [345]:
mat1

array([[19, 31, 39],
       [73, 68, 34],
       [76, 30, 44],
       [51, 72, 46],
       [73, 73, 58]])

In [347]:
np.where(mat>=50)

(array([ 3,  4,  6,  9, 10, 12, 13, 14], dtype=int64),)

In [348]:
age = 50
np.where(age >60,"Retired", "Still working")

array('Still working', dtype='<U13')

In [349]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

In [350]:
mat1

array([[6, 8, 7],
       [2, 2, 8],
       [2, 7, 9]])

In [351]:
mat2

array([[2, 6, 3],
       [3, 5, 9],
       [8, 2, 6]])

In [352]:
mat1/mat2

array([[3.        , 1.33333333, 2.33333333],
       [0.66666667, 0.4       , 0.88888889],
       [0.25      , 3.5       , 1.5       ]])

In [353]:
print("\n Linear combination : 3*A - 2*B \n",3*mat1-2*mat2)


 Linear combination : 3*A - 2*B 
 [[ 14  12  15]
 [  0  -4   6]
 [-10  17  15]]


In [355]:
start = np.zeros((3,3))

In [356]:
start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [358]:
add_row = np.array([1,0,3])

In [359]:
added = start+add_row

In [360]:
added

array([[1., 0., 3.],
       [1., 0., 3.],
       [1., 0., 3.]])

In [362]:
add_rows = add_row.T

In [363]:
add_rows

array([1, 0, 3])